import Head from 'next/head'

import { useSession, getSession, getProviders } from 'next-auth/react'

export default function Home () {
  const { data: session } = useSession()

  if (!session) return <h2>Este es la página de login</h2>
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </>
  )
}

export async function getServerSideProps (context) {
  const session = getSession()
  const providers = getProviders(context)

  return {
    props: {
      session,
      providers
    }
  }
}
